// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdrQ1GI_704W0ThhVHTqYE0VDboNOK1TY',
    appId: '1:61551482062:web:YOUR_WEB_APP_ID',
    messagingSenderId: '61551482062',
    projectId: 'alondraapp-e9c61',
    authDomain: 'alondraapp-e9c61.firebaseapp.com',
    storageBucket: 'alondraapp-e9c61.firebasestorage.app',
    measurementId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrQ1GI_704W0ThhVHTqYE0VDboNOK1TY',
    appId: '1:61551482062:android:f23a1cf6e1f1017c1aec9f',
    messagingSenderId: '61551482062',
    projectId: 'alondraapp-e9c61',
    storageBucket: 'alondraapp-e9c61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBgyJoJMVVrCewaOPgtBrvdfQQsJnlx1E',
    appId: '1:61551482062:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '61551482062',
    projectId: 'alondraapp-e9c61',
    storageBucket: 'alondraapp-e9c61.firebasestorage.app',
    androidClientId: '',
    iosClientId: '',
    iosBundleId: 'alondra.multivendor.customer',
  );
}
